framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(default:messenger_transport_dsn:MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            transcription:
                dsn: '%env(default:messenger_transport_dsn:MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 60000
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\PingTranscriptionMessage: transcription
            App\Message\TranscribeRecordingMessage: transcription
