<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614161321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store transcript segments with call leg attribution and raw payloads for live transcription debugging';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE call_transcript_segment (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, provider_event_id VARCHAR(255) DEFAULT NULL, speaker_role VARCHAR(50) DEFAULT NULL, text TEXT NOT NULL, is_final BOOLEAN DEFAULT true NOT NULL, raw_payload JSONB DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_transcript_id BIGINT NOT NULL, call_session_id BIGINT DEFAULT NULL, call_leg_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_call_transcript_segment_transcript ON call_transcript_segment (call_transcript_id)');
        $this->addSql('CREATE INDEX idx_call_transcript_segment_session ON call_transcript_segment (call_session_id)');
        $this->addSql('CREATE INDEX idx_call_transcript_segment_leg ON call_transcript_segment (call_leg_id)');
        $this->addSql('CREATE INDEX idx_call_transcript_segment_sequence ON call_transcript_segment (sequence_number)');
        $this->addSql('ALTER TABLE call_transcript_segment ADD CONSTRAINT FK_3D482379DDA3F3AD FOREIGN KEY (call_transcript_id) REFERENCES call_transcript (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_transcript_segment ADD CONSTRAINT FK_3D48237945A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_transcript_segment ADD CONSTRAINT FK_3D482379650F9405 FOREIGN KEY (call_leg_id) REFERENCES call_leg (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE call_transcript_segment DROP CONSTRAINT FK_3D482379DDA3F3AD');
        $this->addSql('ALTER TABLE call_transcript_segment DROP CONSTRAINT FK_3D48237945A0AD45');
        $this->addSql('ALTER TABLE call_transcript_segment DROP CONSTRAINT FK_3D482379650F9405');
        $this->addSql('DROP TABLE call_transcript_segment');
    }
}
