<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260616005000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add CRM phase 6C field notes and equipment service history';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE job ADD COLUMN IF NOT EXISTS technician_notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE job ADD COLUMN IF NOT EXISTS recommended_repair_notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE job ADD COLUMN IF NOT EXISTS recommended_replacement_notes TEXT DEFAULT NULL');

        $this->addSql('CREATE TABLE IF NOT EXISTS equipment_service_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, equipment_id BIGINT DEFAULT NULL, job_id BIGINT DEFAULT NULL, task_id BIGINT DEFAULT NULL, technician_id BIGINT DEFAULT NULL, arrived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, technician_notes TEXT DEFAULT NULL, recommended_repair_notes TEXT DEFAULT NULL, recommended_replacement_notes TEXT DEFAULT NULL, service_type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_equipment_service_record_tenant ON equipment_service_record (tenant_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_equipment_service_record_property ON equipment_service_record (property_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_equipment_service_record_equipment ON equipment_service_record (equipment_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_equipment_service_record_job ON equipment_service_record (job_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_equipment_service_record_completed_at ON equipment_service_record (completed_at)');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F04EEC85D FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F03414710B FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F07A0C2E8B FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F0989F1FD FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F0BE1E5AF FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_service_record ADD CONSTRAINT FK_5D69A2F0D2D9B32A FOREIGN KEY (technician_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F0D2D9B32A');
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F0BE1E5AF');
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F0989F1FD');
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F07A0C2E8B');
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F03414710B');
        $this->addSql('ALTER TABLE equipment_service_record DROP CONSTRAINT IF EXISTS FK_5D69A2F04EEC85D');
        $this->addSql('DROP TABLE IF EXISTS equipment_service_record');
        $this->addSql('ALTER TABLE job DROP COLUMN IF EXISTS arrived_at');
        $this->addSql('ALTER TABLE job DROP COLUMN IF EXISTS technician_notes');
        $this->addSql('ALTER TABLE job DROP COLUMN IF EXISTS recommended_repair_notes');
        $this->addSql('ALTER TABLE job DROP COLUMN IF EXISTS recommended_replacement_notes');
    }
}
