<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260613172647 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE click_to_call_request (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, agent_number VARCHAR(255) NOT NULL, target_number VARCHAR(255) NOT NULL, target_name VARCHAR(255) DEFAULT NULL, from_number VARCHAR(255) NOT NULL, connection_id VARCHAR(255) NOT NULL, agent_call_control_id VARCHAR(255) DEFAULT NULL, agent_call_leg_id VARCHAR(255) DEFAULT NULL, target_call_control_id VARCHAR(255) DEFAULT NULL, target_call_leg_id VARCHAR(255) DEFAULT NULL, bridge_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recording_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, client_state_token VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_session_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_702BAABF2CEF000C ON click_to_call_request (client_state_token)');
        $this->addSql('CREATE INDEX IDX_702BAABF45A0AD45 ON click_to_call_request (call_session_id)');
        $this->addSql('CREATE INDEX idx_click_to_call_request_status ON click_to_call_request (status)');
        $this->addSql('CREATE INDEX idx_click_to_call_request_client_state_token ON click_to_call_request (client_state_token)');
        $this->addSql('CREATE INDEX idx_click_to_call_request_agent_call_leg_id ON click_to_call_request (agent_call_leg_id)');
        $this->addSql('CREATE INDEX idx_click_to_call_request_target_call_leg_id ON click_to_call_request (target_call_leg_id)');
        $this->addSql('CREATE INDEX idx_click_to_call_request_created_at ON click_to_call_request (created_at)');
        $this->addSql('ALTER TABLE click_to_call_request ADD CONSTRAINT FK_702BAABF45A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_leg ADD role VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE call_leg ADD dial_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_recording ADD channel_mapping JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD flow_type VARCHAR(50) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE click_to_call_request DROP CONSTRAINT FK_702BAABF45A0AD45');
        $this->addSql('DROP TABLE click_to_call_request');
        $this->addSql('ALTER TABLE call_leg DROP role');
        $this->addSql('ALTER TABLE call_leg DROP dial_order');
        $this->addSql('ALTER TABLE call_recording DROP channel_mapping');
        $this->addSql('ALTER TABLE call_session DROP flow_type');
    }
}
