<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add maintenance_plan and property_maintenance_plan entities for CRM Phase 10C.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('maintenance_plan')) {
            $this->addSql('CREATE TABLE maintenance_plan (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                name VARCHAR(100) NOT NULL,
                plan_type VARCHAR(20) NOT NULL,
                visit_frequency_days INT NOT NULL,
                discount_percentage INT NOT NULL DEFAULT 0,
                priority_scheduling BOOLEAN NOT NULL DEFAULT false,
                included_services JSON DEFAULT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true,
                start_date DATE DEFAULT NULL,
                renewal_date DATE DEFAULT NULL,
                cancellation_date DATE DEFAULT NULL,
                notes TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_maintenance_plan_tenant ON maintenance_plan (tenant_id)');
        }

        if (!$schema->hasTable('property_maintenance_plan')) {
            $this->addSql('CREATE TABLE property_maintenance_plan (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                property_id BIGINT NOT NULL,
                maintenance_plan_id BIGINT NOT NULL,
                plan_name_at_assignment VARCHAR(255) NOT NULL,
                is_cancelled BOOLEAN NOT NULL DEFAULT false,
                cancellation_date DATE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_pmp_tenant ON property_maintenance_plan (tenant_id)');
            $this->addSql('CREATE INDEX idx_pmp_property ON property_maintenance_plan (property_id)');

            $this->addSql('ALTER TABLE maintenance_plan ADD CONSTRAINT FK_MAINTENANCE_PLAN_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE property_maintenance_plan ADD CONSTRAINT FK_PMP_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE property_maintenance_plan ADD CONSTRAINT FK_PMP_PROPERTY FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE property_maintenance_plan ADD CONSTRAINT FK_PMP_MAINTENANCE_PLAN FOREIGN KEY (maintenance_plan_id) REFERENCES maintenance_plan(id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE property_maintenance_plan DROP FOREIGN KEY FK_PMP_TENANT');
        $this->addSql('ALTER TABLE property_maintenance_plan DROP FOREIGN KEY FK_PMP_PROPERTY');
        $this->addSql('ALTER TABLE property_maintenance_plan DROP FOREIGN KEY FK_PMP_MAINTENANCE_PLAN');
        $this->addSql('DROP TABLE property_maintenance_plan');
        $this->addSql('DROP TABLE maintenance_plan');
    }
}
