<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613142606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Telnyx recording metadata and application-managed S3 import tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE call_recording (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) DEFAULT \'telnyx\' NOT NULL, provider_recording_id VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, s3_bucket VARCHAR(255) DEFAULT NULL, s3_key TEXT DEFAULT NULL, content_type VARCHAR(255) DEFAULT NULL, format VARCHAR(20) DEFAULT NULL, duration_seconds INT DEFAULT NULL, size_bytes BIGINT DEFAULT NULL, recording_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recording_ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, import_error TEXT DEFAULT NULL, provider_download_url TEXT DEFAULT NULL, raw_payload JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_session_id BIGINT NOT NULL, call_leg_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_90B117A0DFDFA4F8 ON call_recording (provider_recording_id)');
        $this->addSql('CREATE INDEX IDX_90B117A045A0AD45 ON call_recording (call_session_id)');
        $this->addSql('CREATE INDEX IDX_90B117A0650F9405 ON call_recording (call_leg_id)');
        $this->addSql('CREATE INDEX idx_call_recording_status ON call_recording (status)');
        $this->addSql('CREATE INDEX idx_call_recording_storage ON call_recording (s3_bucket, s3_key)');
        $this->addSql('CREATE INDEX idx_call_recording_created_at ON call_recording (created_at)');
        $this->addSql('ALTER TABLE call_recording ADD CONSTRAINT FK_90B117A045A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_recording ADD CONSTRAINT FK_90B117A0650F9405 FOREIGN KEY (call_leg_id) REFERENCES call_leg (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE call_recording DROP CONSTRAINT FK_90B117A045A0AD45');
        $this->addSql('ALTER TABLE call_recording DROP CONSTRAINT FK_90B117A0650F9405');
        $this->addSql('DROP TABLE call_recording');
    }
}
