<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add next_best_action_suggestion for CRM Phase 10H.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('next_best_action_suggestion')) {
            $this->addSql('CREATE TABLE next_best_action_suggestion (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                property_id BIGINT NOT NULL,
                opportunity_id BIGINT DEFAULT NULL,
                suggestion_type VARCHAR(50) NOT NULL,
                source_key VARCHAR(255) NOT NULL,
                reason TEXT NOT NULL,
                confidence VARCHAR(20) NOT NULL DEFAULT \'medium\',
                status VARCHAR(20) NOT NULL DEFAULT \'suggested\',
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_next_best_action_tenant ON next_best_action_suggestion (tenant_id)');
            $this->addSql('CREATE INDEX idx_next_best_action_property ON next_best_action_suggestion (property_id)');
            $this->addSql('CREATE INDEX idx_next_best_action_status ON next_best_action_suggestion (status)');
            $this->addSql('CREATE INDEX idx_next_best_action_type ON next_best_action_suggestion (suggestion_type)');
            $this->addSql('CREATE UNIQUE INDEX uniq_next_best_action_source ON next_best_action_suggestion (tenant_id, property_id, suggestion_type, source_key)');

            $this->addSql('ALTER TABLE next_best_action_suggestion ADD CONSTRAINT FK_NEXT_BEST_ACTION_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE next_best_action_suggestion ADD CONSTRAINT FK_NEXT_BEST_ACTION_PROPERTY FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE next_best_action_suggestion ADD CONSTRAINT FK_NEXT_BEST_ACTION_OPPORTUNITY FOREIGN KEY (opportunity_id) REFERENCES retention_opportunity(id) ON DELETE SET NULL');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE next_best_action_suggestion DROP CONSTRAINT FK_NEXT_BEST_ACTION_TENANT');
        $this->addSql('ALTER TABLE next_best_action_suggestion DROP CONSTRAINT FK_NEXT_BEST_ACTION_PROPERTY');
        $this->addSql('ALTER TABLE next_best_action_suggestion DROP CONSTRAINT FK_NEXT_BEST_ACTION_OPPORTUNITY');
        $this->addSql('DROP TABLE next_best_action_suggestion');
    }
}
