<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615030238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_user_id VARCHAR(255) DEFAULT NULL, actor_display VARCHAR(255) DEFAULT NULL, entity_type VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL, before_data JSONB DEFAULT NULL, after_data JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_log_tenant ON audit_log (tenant_id)');
        $this->addSql('CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_log_created_at ON audit_log (created_at)');
        $this->addSql('CREATE TABLE contact (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, display_name VARCHAR(255) NOT NULL, primary_phone VARCHAR(255) DEFAULT NULL, primary_email VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_contact_tenant ON contact (tenant_id)');
        $this->addSql('CREATE INDEX idx_contact_display_name ON contact (display_name)');
        $this->addSql('CREATE TABLE equipment (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, equipment_type VARCHAR(50) NOT NULL, brand VARCHAR(255) DEFAULT NULL, model_number VARCHAR(255) DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, installed_at DATE DEFAULT NULL, warranty_expires_at DATE DEFAULT NULL, status VARCHAR(50) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_equipment_tenant ON equipment (tenant_id)');
        $this->addSql('CREATE INDEX idx_equipment_property ON equipment (property_id)');
        $this->addSql('CREATE TABLE estimate (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, title VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, subtotal_cents INT DEFAULT 0 NOT NULL, tax_cents INT DEFAULT 0 NOT NULL, total_cents INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, contact_id BIGINT DEFAULT NULL, rfq_invitation_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2EA4607E7A1254A ON estimate (contact_id)');
        $this->addSql('CREATE INDEX IDX_D2EA460771A60937 ON estimate (rfq_invitation_id)');
        $this->addSql('CREATE INDEX idx_estimate_tenant ON estimate (tenant_id)');
        $this->addSql('CREATE INDEX idx_estimate_property ON estimate (property_id)');
        $this->addSql('CREATE INDEX idx_estimate_status ON estimate (status)');
        $this->addSql('CREATE TABLE estimate_line_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, quantity NUMERIC(10, 2) NOT NULL, unit_price_cents INT NOT NULL, total_cents INT NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, estimate_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_estimate_line_item_tenant ON estimate_line_item (tenant_id)');
        $this->addSql('CREATE INDEX idx_estimate_line_item_estimate ON estimate_line_item (estimate_id)');
        $this->addSql('CREATE TABLE invoice (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_number VARCHAR(64) NOT NULL, status VARCHAR(50) NOT NULL, issued_at DATE DEFAULT NULL, due_at DATE DEFAULT NULL, subtotal_cents INT DEFAULT 0 NOT NULL, tax_cents INT DEFAULT 0 NOT NULL, total_cents INT DEFAULT 0 NOT NULL, amount_paid_cents INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, contact_id BIGINT DEFAULT NULL, quote_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90651744E7A1254A ON invoice (contact_id)');
        $this->addSql('CREATE INDEX IDX_90651744DB805178 ON invoice (quote_id)');
        $this->addSql('CREATE INDEX idx_invoice_tenant ON invoice (tenant_id)');
        $this->addSql('CREATE INDEX idx_invoice_property ON invoice (property_id)');
        $this->addSql('CREATE INDEX idx_invoice_status ON invoice (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_invoice_number ON invoice (invoice_number)');
        $this->addSql('CREATE TABLE invoice_line_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, quantity NUMERIC(10, 2) NOT NULL, unit_price_cents INT NOT NULL, total_cents INT NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, invoice_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_invoice_line_item_tenant ON invoice_line_item (tenant_id)');
        $this->addSql('CREATE INDEX idx_invoice_line_item_invoice ON invoice_line_item (invoice_id)');
        $this->addSql('CREATE TABLE property (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) NOT NULL, province VARCHAR(120) NOT NULL, postal_code VARCHAR(32) NOT NULL, country VARCHAR(2) DEFAULT \'CA\' NOT NULL, property_type VARCHAR(100) DEFAULT NULL, approximate_square_feet INT DEFAULT NULL, year_built INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_property_tenant ON property (tenant_id)');
        $this->addSql('CREATE INDEX idx_property_tenant_city ON property (tenant_id, city)');
        $this->addSql('CREATE INDEX idx_property_tenant_postal_code ON property (tenant_id, postal_code)');
        $this->addSql('CREATE TABLE property_contact (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, relationship_type VARCHAR(50) NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, contact_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_property_contact_tenant ON property_contact (tenant_id)');
        $this->addSql('CREATE INDEX idx_property_contact_property ON property_contact (property_id)');
        $this->addSql('CREATE INDEX idx_property_contact_contact ON property_contact (contact_id)');
        $this->addSql('CREATE TABLE quote (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quote_number VARCHAR(64) NOT NULL, status VARCHAR(50) NOT NULL, valid_until DATE DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, subtotal_cents INT DEFAULT 0 NOT NULL, tax_cents INT DEFAULT 0 NOT NULL, total_cents INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, contact_id BIGINT DEFAULT NULL, estimate_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B71CBF4E7A1254A ON quote (contact_id)');
        $this->addSql('CREATE INDEX IDX_6B71CBF485F23082 ON quote (estimate_id)');
        $this->addSql('CREATE INDEX idx_quote_tenant ON quote (tenant_id)');
        $this->addSql('CREATE INDEX idx_quote_property ON quote (property_id)');
        $this->addSql('CREATE INDEX idx_quote_status ON quote (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_quote_number ON quote (quote_number)');
        $this->addSql('CREATE TABLE quote_line_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, quantity NUMERIC(10, 2) NOT NULL, unit_price_cents INT NOT NULL, total_cents INT NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, quote_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_quote_line_item_tenant ON quote_line_item (tenant_id)');
        $this->addSql('CREATE INDEX idx_quote_line_item_quote ON quote_line_item (quote_id)');
        $this->addSql('CREATE TABLE rfq (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_reference VARCHAR(255) DEFAULT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) NOT NULL, province VARCHAR(120) NOT NULL, postal_code VARCHAR(32) NOT NULL, country VARCHAR(2) DEFAULT \'CA\' NOT NULL, customer_name VARCHAR(255) DEFAULT NULL, customer_phone VARCHAR(255) DEFAULT NULL, customer_email VARCHAR(255) DEFAULT NULL, project_type VARCHAR(120) DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rfq_status ON rfq (status)');
        $this->addSql('CREATE INDEX idx_rfq_created_at ON rfq (created_at)');
        $this->addSql('CREATE TABLE rfq_invitation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, declined_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id BIGINT NOT NULL, rfq_id BIGINT NOT NULL, created_property_id BIGINT DEFAULT NULL, created_estimate_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3292E601ABD9545F ON rfq_invitation (rfq_id)');
        $this->addSql('CREATE INDEX IDX_3292E601F5E2049B ON rfq_invitation (created_property_id)');
        $this->addSql('CREATE INDEX IDX_3292E601248227F5 ON rfq_invitation (created_estimate_id)');
        $this->addSql('CREATE INDEX idx_rfq_invitation_tenant ON rfq_invitation (tenant_id)');
        $this->addSql('CREATE INDEX idx_rfq_invitation_status ON rfq_invitation (status)');
        $this->addSql('CREATE TABLE tenant (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, legal_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tenant_name ON tenant (name)');
        $this->addSql('CREATE TABLE "user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, display_name VARCHAR(255) DEFAULT NULL, cell_phone VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_tenant_membership (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSONB NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, tenant_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86A13F06A76ED395 ON user_tenant_membership (user_id)');
        $this->addSql('CREATE INDEX idx_user_tenant_membership_tenant ON user_tenant_membership (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_tenant_membership_user_tenant ON user_tenant_membership (user_id, tenant_id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F59033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6389033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D5839033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate ADD CONSTRAINT FK_D2EA46079033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate ADD CONSTRAINT FK_D2EA4607549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate ADD CONSTRAINT FK_D2EA4607E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate ADD CONSTRAINT FK_D2EA460771A60937 FOREIGN KEY (rfq_invitation_id) REFERENCES rfq_invitation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate_line_item ADD CONSTRAINT FK_B8D23DEB9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE estimate_line_item ADD CONSTRAINT FK_B8D23DEB85F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line_item ADD CONSTRAINT FK_F1F9275B9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line_item ADD CONSTRAINT FK_F1F9275B2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contact ADD CONSTRAINT FK_15AFAC409033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contact ADD CONSTRAINT FK_15AFAC40549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_contact ADD CONSTRAINT FK_15AFAC40E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF485F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_line_item ADD CONSTRAINT FK_13B44FBD9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_line_item ADD CONSTRAINT FK_13B44FBDDB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rfq_invitation ADD CONSTRAINT FK_3292E6019033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rfq_invitation ADD CONSTRAINT FK_3292E601ABD9545F FOREIGN KEY (rfq_id) REFERENCES rfq (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rfq_invitation ADD CONSTRAINT FK_3292E601F5E2049B FOREIGN KEY (created_property_id) REFERENCES property (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rfq_invitation ADD CONSTRAINT FK_3292E601248227F5 FOREIGN KEY (created_estimate_id) REFERENCES estimate (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant_membership ADD CONSTRAINT FK_86A13F06A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant_membership ADD CONSTRAINT FK_86A13F069033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD tenant_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD property_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD contact_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD rfq_invitation_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD estimate_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD quote_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD invoice_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE19033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE1549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE1E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE171A60937 FOREIGN KEY (rfq_invitation_id) REFERENCES rfq_invitation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE185F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE1DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_session ADD CONSTRAINT FK_5E14CE12989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5E14CE19033212A ON call_session (tenant_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE1549213EC ON call_session (property_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE1E7A1254A ON call_session (contact_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE171A60937 ON call_session (rfq_invitation_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE185F23082 ON call_session (estimate_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE1DB805178 ON call_session (quote_id)');
        $this->addSql('CREATE INDEX IDX_5E14CE12989F1FD ON call_session (invoice_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F59033212A');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6389033212A');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D5839033212A');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583549213EC');
        $this->addSql('ALTER TABLE estimate DROP CONSTRAINT FK_D2EA46079033212A');
        $this->addSql('ALTER TABLE estimate DROP CONSTRAINT FK_D2EA4607549213EC');
        $this->addSql('ALTER TABLE estimate DROP CONSTRAINT FK_D2EA4607E7A1254A');
        $this->addSql('ALTER TABLE estimate DROP CONSTRAINT FK_D2EA460771A60937');
        $this->addSql('ALTER TABLE estimate_line_item DROP CONSTRAINT FK_B8D23DEB9033212A');
        $this->addSql('ALTER TABLE estimate_line_item DROP CONSTRAINT FK_B8D23DEB85F23082');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517449033212A');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744549213EC');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744E7A1254A');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744DB805178');
        $this->addSql('ALTER TABLE invoice_line_item DROP CONSTRAINT FK_F1F9275B9033212A');
        $this->addSql('ALTER TABLE invoice_line_item DROP CONSTRAINT FK_F1F9275B2989F1FD');
        $this->addSql('ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE9033212A');
        $this->addSql('ALTER TABLE property_contact DROP CONSTRAINT FK_15AFAC409033212A');
        $this->addSql('ALTER TABLE property_contact DROP CONSTRAINT FK_15AFAC40549213EC');
        $this->addSql('ALTER TABLE property_contact DROP CONSTRAINT FK_15AFAC40E7A1254A');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF49033212A');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF4549213EC');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF4E7A1254A');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF485F23082');
        $this->addSql('ALTER TABLE quote_line_item DROP CONSTRAINT FK_13B44FBD9033212A');
        $this->addSql('ALTER TABLE quote_line_item DROP CONSTRAINT FK_13B44FBDDB805178');
        $this->addSql('ALTER TABLE rfq_invitation DROP CONSTRAINT FK_3292E6019033212A');
        $this->addSql('ALTER TABLE rfq_invitation DROP CONSTRAINT FK_3292E601ABD9545F');
        $this->addSql('ALTER TABLE rfq_invitation DROP CONSTRAINT FK_3292E601F5E2049B');
        $this->addSql('ALTER TABLE rfq_invitation DROP CONSTRAINT FK_3292E601248227F5');
        $this->addSql('ALTER TABLE user_tenant_membership DROP CONSTRAINT FK_86A13F06A76ED395');
        $this->addSql('ALTER TABLE user_tenant_membership DROP CONSTRAINT FK_86A13F069033212A');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE estimate');
        $this->addSql('DROP TABLE estimate_line_item');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_line_item');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE property_contact');
        $this->addSql('DROP TABLE quote');
        $this->addSql('DROP TABLE quote_line_item');
        $this->addSql('DROP TABLE rfq');
        $this->addSql('DROP TABLE rfq_invitation');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_tenant_membership');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE19033212A');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE1549213EC');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE1E7A1254A');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE171A60937');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE185F23082');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE1DB805178');
        $this->addSql('ALTER TABLE call_session DROP CONSTRAINT FK_5E14CE12989F1FD');
        $this->addSql('DROP INDEX IDX_5E14CE19033212A');
        $this->addSql('DROP INDEX IDX_5E14CE1549213EC');
        $this->addSql('DROP INDEX IDX_5E14CE1E7A1254A');
        $this->addSql('DROP INDEX IDX_5E14CE171A60937');
        $this->addSql('DROP INDEX IDX_5E14CE185F23082');
        $this->addSql('DROP INDEX IDX_5E14CE1DB805178');
        $this->addSql('DROP INDEX IDX_5E14CE12989F1FD');
        $this->addSql('ALTER TABLE call_session DROP tenant_id');
        $this->addSql('ALTER TABLE call_session DROP property_id');
        $this->addSql('ALTER TABLE call_session DROP contact_id');
        $this->addSql('ALTER TABLE call_session DROP rfq_invitation_id');
        $this->addSql('ALTER TABLE call_session DROP estimate_id');
        $this->addSql('ALTER TABLE call_session DROP quote_id');
        $this->addSql('ALTER TABLE call_session DROP invoice_id');
    }
}
