<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613154601 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add OpenAI call transcript storage for imported recordings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE call_transcript (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) DEFAULT \'openai\' NOT NULL, model VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, transcript_text TEXT DEFAULT NULL, raw_response JSONB DEFAULT NULL, language VARCHAR(32) DEFAULT NULL, duration_seconds INT DEFAULT NULL, error_message TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, failed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_recording_id BIGINT NOT NULL, call_session_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_call_transcript_recording ON call_transcript (call_recording_id)');
        $this->addSql('CREATE INDEX idx_call_transcript_session ON call_transcript (call_session_id)');
        $this->addSql('CREATE INDEX idx_call_transcript_status ON call_transcript (status)');
        $this->addSql('CREATE INDEX idx_call_transcript_created_at ON call_transcript (created_at)');
        $this->addSql('ALTER TABLE call_transcript ADD CONSTRAINT FK_8C6956596DC9F4C FOREIGN KEY (call_recording_id) REFERENCES call_recording (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_transcript ADD CONSTRAINT FK_8C69565945A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE call_transcript DROP CONSTRAINT FK_8C6956596DC9F4C');
        $this->addSql('ALTER TABLE call_transcript DROP CONSTRAINT FK_8C69565945A0AD45');
        $this->addSql('DROP TABLE call_transcript');
    }
}
