<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260616003000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add CRM phase 6A job and task schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS job (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id BIGINT NOT NULL, property_id BIGINT NOT NULL, contact_id BIGINT DEFAULT NULL, quote_id BIGINT DEFAULT NULL, invoice_id BIGINT DEFAULT NULL, equipment_id BIGINT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL DEFAULT \'unscheduled\', scheduled_start_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_reason TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_tenant ON job (tenant_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_property ON job (property_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_contact ON job (contact_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_quote ON job (quote_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_invoice ON job (invoice_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_equipment ON job (equipment_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_status ON job (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_job_scheduled_start_at ON job (scheduled_start_at)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F4EEC85D FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F3414710B FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F1C49F7D3 FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F4C5D5B53 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_6F6A8D4F7A0C2E8B FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE IF NOT EXISTS task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id BIGINT NOT NULL, job_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT \'unscheduled\', scheduled_start_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_task_tenant ON task (tenant_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_task_job ON task (job_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_task_status ON task (status)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_task_scheduled_start_at ON task (scheduled_start_at)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_7A4A7D1B4EEC85D FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_7A4A7D1BBE1E5AF FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE task DROP CONSTRAINT IF EXISTS FK_7A4A7D1BBE1E5AF');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT IF EXISTS FK_7A4A7D1B4EEC85D');
        $this->addSql('DROP TABLE IF EXISTS task');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F7A0C2E8B');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F989F1FD');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F4C5D5B53');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F1C49F7D3');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F3414710B');
        $this->addSql('ALTER TABLE job DROP CONSTRAINT IF EXISTS FK_6F6A8D4F4EEC85D');
        $this->addSql('DROP TABLE IF EXISTS job');
    }
}
