<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add campaign entity for CRM Phase 10D.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('campaign')) {
            $this->addSql('CREATE TABLE campaign (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                name VARCHAR(100) NOT NULL,
                campaign_type VARCHAR(50) NOT NULL,
                audience_description TEXT NOT NULL,
                scheduled_date DATE DEFAULT NULL,
                status VARCHAR(20) NOT NULL DEFAULT \'draft\',
                notes TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_campaign_tenant ON campaign (tenant_id)');
            $this->addSql('CREATE INDEX idx_campaign_status ON campaign (status)');
            $this->addSql('CREATE INDEX idx_campaign_scheduled_date ON campaign (scheduled_date)');

            $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_CAMPAIGN_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_CAMPAIGN_TENANT');
        $this->addSql('DROP TABLE campaign');
    }
}
