<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add CSR playbook attachments for CRM Phase 10E.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('csr_playbook_attachment')) {
            $this->addSql('CREATE TABLE csr_playbook_attachment (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                property_id BIGINT DEFAULT NULL,
                contact_id BIGINT DEFAULT NULL,
                retention_opportunity_id BIGINT DEFAULT NULL,
                playbook_type VARCHAR(50) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_csr_playbook_attachment_tenant ON csr_playbook_attachment (tenant_id)');
            $this->addSql('CREATE INDEX idx_csr_playbook_attachment_property ON csr_playbook_attachment (property_id)');
            $this->addSql('CREATE INDEX idx_csr_playbook_attachment_contact ON csr_playbook_attachment (contact_id)');
            $this->addSql('CREATE INDEX idx_csr_playbook_attachment_opportunity ON csr_playbook_attachment (retention_opportunity_id)');
            $this->addSql('CREATE INDEX idx_csr_playbook_attachment_lookup ON csr_playbook_attachment (tenant_id, playbook_type, property_id, contact_id, retention_opportunity_id)');

            $this->addSql('ALTER TABLE csr_playbook_attachment ADD CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE csr_playbook_attachment ADD CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_PROPERTY FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE csr_playbook_attachment ADD CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_CONTACT FOREIGN KEY (contact_id) REFERENCES contact(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE csr_playbook_attachment ADD CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_RETAIN_OPPORTUNITY FOREIGN KEY (retention_opportunity_id) REFERENCES retention_opportunity(id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE csr_playbook_attachment DROP CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_TENANT');
        $this->addSql('ALTER TABLE csr_playbook_attachment DROP CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_PROPERTY');
        $this->addSql('ALTER TABLE csr_playbook_attachment DROP CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_CONTACT');
        $this->addSql('ALTER TABLE csr_playbook_attachment DROP CONSTRAINT FK_CSR_PLAYBOOK_ATTACHMENT_RETAIN_OPPORTUNITY');
        $this->addSql('DROP TABLE csr_playbook_attachment');
    }
}
