<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add retention_opportunity entity for CRM Phase 10B.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('retention_opportunity')) {
            $this->addSql('CREATE TABLE retention_opportunity (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                property_id BIGINT NOT NULL,
                contact_id BIGINT DEFAULT NULL,
                equipment_id BIGINT DEFAULT NULL,
                opportunity_type VARCHAR(50) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT \'open\',
                source_key VARCHAR(255) NOT NULL,
                detected_reason TEXT NOT NULL,
                detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_retention_opportunity_tenant ON retention_opportunity (tenant_id)');
            $this->addSql('CREATE INDEX idx_retention_opportunity_property ON retention_opportunity (property_id)');
            $this->addSql('CREATE INDEX idx_retention_opportunity_status ON retention_opportunity (status)');
            $this->addSql('CREATE INDEX idx_retention_opportunity_lookup ON retention_opportunity (tenant_id, property_id, opportunity_type, source_key, status)');

            $this->addSql('ALTER TABLE retention_opportunity ADD CONSTRAINT FK_RETENTION_OPPORTUNITY_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE retention_opportunity ADD CONSTRAINT FK_RETENTION_OPPORTUNITY_PROPERTY FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE retention_opportunity ADD CONSTRAINT FK_RETENTION_OPPORTUNITY_CONTACT FOREIGN KEY (contact_id) REFERENCES contact(id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE retention_opportunity ADD CONSTRAINT FK_RETENTION_OPPORTUNITY_EQUIPMENT FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE SET NULL');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE retention_opportunity DROP FOREIGN KEY FK_RETENTION_OPPORTUNITY_TENANT');
        $this->addSql('ALTER TABLE retention_opportunity DROP FOREIGN KEY FK_RETENTION_OPPORTUNITY_PROPERTY');
        $this->addSql('ALTER TABLE retention_opportunity DROP FOREIGN KEY FK_RETENTION_OPPORTUNITY_CONTACT');
        $this->addSql('ALTER TABLE retention_opportunity DROP FOREIGN KEY FK_RETENTION_OPPORTUNITY_EQUIPMENT');
        $this->addSql('DROP TABLE retention_opportunity');
    }
}
