<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add customer sentiment history for CRM Phase 10F.';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('customer_sentiment_history')) {
            $this->addSql('CREATE TABLE customer_sentiment_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tenant_id BIGINT NOT NULL,
                property_id BIGINT NOT NULL,
                contact_id BIGINT DEFAULT NULL,
                call_session_id BIGINT DEFAULT NULL,
                recorded_by_id BIGINT NOT NULL,
                sentiment VARCHAR(50) NOT NULL,
                note TEXT DEFAULT NULL,
                recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_tenant ON customer_sentiment_history (tenant_id)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_property ON customer_sentiment_history (property_id)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_contact ON customer_sentiment_history (contact_id)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_call_session ON customer_sentiment_history (call_session_id)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_recorded_by ON customer_sentiment_history (recorded_by_id)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_recorded_at ON customer_sentiment_history (recorded_at)');
            $this->addSql('CREATE INDEX idx_customer_sentiment_history_lookup ON customer_sentiment_history (tenant_id, property_id, recorded_at)');

            $this->addSql('ALTER TABLE customer_sentiment_history ADD CONSTRAINT FK_CSH_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE customer_sentiment_history ADD CONSTRAINT FK_CSH_PROPERTY FOREIGN KEY (property_id) REFERENCES property(id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE customer_sentiment_history ADD CONSTRAINT FK_CSH_CONTACT FOREIGN KEY (contact_id) REFERENCES contact(id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE customer_sentiment_history ADD CONSTRAINT FK_CSH_CALL_SESSION FOREIGN KEY (call_session_id) REFERENCES call_session(id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE customer_sentiment_history ADD CONSTRAINT FK_CSH_RECORDED_BY FOREIGN KEY (recorded_by_id) REFERENCES "user"(id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer_sentiment_history DROP CONSTRAINT FK_CSH_TENANT');
        $this->addSql('ALTER TABLE customer_sentiment_history DROP CONSTRAINT FK_CSH_PROPERTY');
        $this->addSql('ALTER TABLE customer_sentiment_history DROP CONSTRAINT FK_CSH_CONTACT');
        $this->addSql('ALTER TABLE customer_sentiment_history DROP CONSTRAINT FK_CSH_CALL_SESSION');
        $this->addSql('ALTER TABLE customer_sentiment_history DROP CONSTRAINT FK_CSH_RECORDED_BY');
        $this->addSql('DROP TABLE customer_sentiment_history');
    }
}
