<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260613204907 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE call_summary (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) DEFAULT \'ollama\' NOT NULL, model VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, summary_json JSONB DEFAULT NULL, summary_text TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_transcript_id BIGINT NOT NULL, call_recording_id BIGINT DEFAULT NULL, call_session_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B8DFF56DDA3F3AD ON call_summary (call_transcript_id)');
        $this->addSql('CREATE INDEX IDX_1B8DFF566DC9F4C ON call_summary (call_recording_id)');
        $this->addSql('CREATE INDEX IDX_1B8DFF5645A0AD45 ON call_summary (call_session_id)');
        $this->addSql('CREATE INDEX idx_call_summary_status ON call_summary (status)');
        $this->addSql('CREATE INDEX idx_call_summary_created_at ON call_summary (created_at)');
        $this->addSql('CREATE TABLE transcription_job (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) DEFAULT \'local_worker\' NOT NULL, status VARCHAR(50) NOT NULL, priority INT DEFAULT 0 NOT NULL, attempts INT DEFAULT 0 NOT NULL, max_attempts INT DEFAULT 3 NOT NULL, locked_by VARCHAR(255) DEFAULT NULL, locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, failed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, input_s3_bucket VARCHAR(255) NOT NULL, input_s3_key TEXT NOT NULL, channel_mapping JSONB DEFAULT NULL, transcript_text TEXT DEFAULT NULL, transcript_json JSONB DEFAULT NULL, transcript_s3_bucket VARCHAR(255) DEFAULT NULL, transcript_s3_key TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_recording_id BIGINT NOT NULL, call_session_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6798A7D745A0AD45 ON transcription_job (call_session_id)');
        $this->addSql('CREATE INDEX idx_transcription_job_status ON transcription_job (status)');
        $this->addSql('CREATE INDEX idx_transcription_job_next_attempt_at ON transcription_job (next_attempt_at)');
        $this->addSql('CREATE INDEX idx_transcription_job_locked_until ON transcription_job (locked_until)');
        $this->addSql('CREATE INDEX idx_transcription_job_priority ON transcription_job (priority)');
        $this->addSql('CREATE INDEX idx_transcription_job_created_at ON transcription_job (created_at)');
        $this->addSql('CREATE INDEX idx_transcription_job_call_recording ON transcription_job (call_recording_id)');
        $this->addSql('ALTER TABLE call_summary ADD CONSTRAINT FK_1B8DFF56DDA3F3AD FOREIGN KEY (call_transcript_id) REFERENCES call_transcript (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_summary ADD CONSTRAINT FK_1B8DFF566DC9F4C FOREIGN KEY (call_recording_id) REFERENCES call_recording (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_summary ADD CONSTRAINT FK_1B8DFF5645A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transcription_job ADD CONSTRAINT FK_6798A7D76DC9F4C FOREIGN KEY (call_recording_id) REFERENCES call_recording (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transcription_job ADD CONSTRAINT FK_6798A7D745A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_transcript ADD channel_mapping JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE call_transcript ADD transcription_job_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE call_transcript ALTER provider SET DEFAULT \'local_worker\'');
        $this->addSql('ALTER TABLE call_transcript ALTER model DROP NOT NULL');
        $this->addSql('ALTER TABLE call_transcript ADD CONSTRAINT FK_8C695659F115D7BA FOREIGN KEY (transcription_job_id) REFERENCES transcription_job (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8C695659F115D7BA ON call_transcript (transcription_job_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE call_summary DROP CONSTRAINT FK_1B8DFF56DDA3F3AD');
        $this->addSql('ALTER TABLE call_summary DROP CONSTRAINT FK_1B8DFF566DC9F4C');
        $this->addSql('ALTER TABLE call_summary DROP CONSTRAINT FK_1B8DFF5645A0AD45');
        $this->addSql('ALTER TABLE transcription_job DROP CONSTRAINT FK_6798A7D76DC9F4C');
        $this->addSql('ALTER TABLE transcription_job DROP CONSTRAINT FK_6798A7D745A0AD45');
        $this->addSql('DROP TABLE call_summary');
        $this->addSql('DROP TABLE transcription_job');
        $this->addSql('ALTER TABLE call_transcript DROP CONSTRAINT FK_8C695659F115D7BA');
        $this->addSql('DROP INDEX IDX_8C695659F115D7BA');
        $this->addSql('ALTER TABLE call_transcript DROP channel_mapping');
        $this->addSql('ALTER TABLE call_transcript DROP transcription_job_id');
        $this->addSql('ALTER TABLE call_transcript ALTER provider SET DEFAULT \'openai\'');
        $this->addSql('ALTER TABLE call_transcript ALTER model SET NOT NULL');
    }
}
