<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260613133736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add durable call sessions, legs, actions, event relationships, and lookup indexes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE call_action (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, request_payload JSONB DEFAULT NULL, response_payload JSONB DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_session_id BIGINT DEFAULT NULL, call_leg_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_82145DB045A0AD45 ON call_action (call_session_id)');
        $this->addSql('CREATE INDEX IDX_82145DB0650F9405 ON call_action (call_leg_id)');
        $this->addSql('CREATE TABLE call_leg (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_leg_id VARCHAR(255) NOT NULL, call_control_id VARCHAR(255) DEFAULT NULL, connection_id VARCHAR(255) DEFAULT NULL, direction VARCHAR(50) DEFAULT NULL, from_number VARCHAR(255) DEFAULT NULL, to_number VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, answered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hangup_cause VARCHAR(255) DEFAULT NULL, hangup_source VARCHAR(255) DEFAULT NULL, sip_hangup_cause VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_session_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2C8C2CA4F7E6A6B7 ON call_leg (provider_leg_id)');
        $this->addSql('CREATE INDEX IDX_2C8C2CA445A0AD45 ON call_leg (call_session_id)');
        $this->addSql('CREATE INDEX idx_call_leg_call_control_id ON call_leg (call_control_id)');
        $this->addSql('CREATE TABLE call_session (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) DEFAULT \'telnyx\' NOT NULL, provider_session_id VARCHAR(255) NOT NULL, inbound_from VARCHAR(255) DEFAULT NULL, inbound_to VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, answered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_event_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hangup_cause VARCHAR(255) DEFAULT NULL, hangup_source VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E14CE14489A067 ON call_session (provider_session_id)');
        $this->addSql('ALTER TABLE call_action ADD CONSTRAINT FK_82145DB045A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_action ADD CONSTRAINT FK_82145DB0650F9405 FOREIGN KEY (call_leg_id) REFERENCES call_leg (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_leg ADD CONSTRAINT FK_2C8C2CA445A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telnyx_event ADD call_session_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE telnyx_event ADD call_leg_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE telnyx_event ADD CONSTRAINT FK_4EACAB3945A0AD45 FOREIGN KEY (call_session_id) REFERENCES call_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telnyx_event ADD CONSTRAINT FK_4EACAB39650F9405 FOREIGN KEY (call_leg_id) REFERENCES call_leg (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4EACAB3945A0AD45 ON telnyx_event (call_session_id)');
        $this->addSql('CREATE INDEX IDX_4EACAB39650F9405 ON telnyx_event (call_leg_id)');
        $this->addSql('CREATE INDEX idx_telnyx_event_event_type ON telnyx_event (event_type)');
        $this->addSql('CREATE INDEX idx_telnyx_event_received_at ON telnyx_event (received_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE call_action DROP CONSTRAINT FK_82145DB045A0AD45');
        $this->addSql('ALTER TABLE call_action DROP CONSTRAINT FK_82145DB0650F9405');
        $this->addSql('ALTER TABLE call_leg DROP CONSTRAINT FK_2C8C2CA445A0AD45');
        $this->addSql('DROP TABLE call_action');
        $this->addSql('DROP TABLE call_leg');
        $this->addSql('DROP TABLE call_session');
        $this->addSql('ALTER TABLE telnyx_event DROP CONSTRAINT FK_4EACAB3945A0AD45');
        $this->addSql('ALTER TABLE telnyx_event DROP CONSTRAINT FK_4EACAB39650F9405');
        $this->addSql('DROP INDEX IDX_4EACAB3945A0AD45');
        $this->addSql('DROP INDEX IDX_4EACAB39650F9405');
        $this->addSql('DROP INDEX idx_telnyx_event_event_type');
        $this->addSql('DROP INDEX idx_telnyx_event_received_at');
        $this->addSql('ALTER TABLE telnyx_event DROP call_session_id');
        $this->addSql('ALTER TABLE telnyx_event DROP call_leg_id');
    }
}
